// <auto-generated />
using System;
using GymPower.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymPower.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251209233431_AddUserFitnessFields")]
    partial class AddUserFitnessFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("GymPower.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("GymPower.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GymPower.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("GymPower.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecommendedForMaintenance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecommendedForMassGain")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecommendedForWeightLoss")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Изграждане на мускулна маса",
                            Description = "Класически протеин за покачване на чиста мускулна маса и възстановяване.",
                            ImageUrl = "/products/wheyprotein.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Този висококачествен суроватъчен протеин е идеалният избор за всеки спортуващ. Съдържа оптимален профил на аминокиселини, които подпомагат бързото възстановяване след тренировка и стимулират мускулния растеж. Приемайте една доза (30г) сутрин на гладно или веднага след тренировка за най-добри резултати.",
                            Name = "Суроватъчен протеин",
                            Price = 69.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "Изграждане на мускулна маса",
                            Description = "Формула с високо съдържание на калории и въглехидрати за бързо покачване на тегло.",
                            ImageUrl = "/products/massgainer.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Mass Gainer е специално разработен за тези, които трудно покачват килограми („хардгейнъри“). Със своята формула, богата на комплексни въглехидрати и висококачествен протеин, той осигурява необходимите калории за изграждане на масивна мускулатура. Идеален за прием след тренировка или като междинно хранене.",
                            Name = "Mass Gainer",
                            Price = 84.90m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            Category = "Изграждане на мускулна маса",
                            Description = "Аминокиселини с разклонена верига за по-добра мускулна регенерация.",
                            ImageUrl = "/products/BCAAcomplex.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "BCAA Complex предоставя незаменимите аминокиселини Левцин, Изолевцин и Валин в оптимално съотношение 2:1:1. Те предпазват мускулите от разграждане (катаболизъм) по време на интензивни тренировки и ускоряват възстановяването. Приемайте преди, по време или след тренировка.",
                            Name = "BCAA Complex",
                            Price = 44.90m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 4,
                            Category = "Изграждане на мускулна маса",
                            Description = "Бавноусвоим протеин, идеален преди сън за дълготрайно възстановяване.",
                            ImageUrl = "/products/gaseinprotein.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Мицеларният казеин е протеин с бавно освобождаване, който подхранва мускулите ви в продължение на до 8 часа. Той е перфектният избор за прием преди лягане, осигурявайки постоянен приток на аминокиселини през нощта, когато тялото се възстановява най-активно.",
                            Name = "Casein Protein",
                            Price = 59.90m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 5,
                            Category = "Отслабване",
                            Description = "Термогенна формула, която подпомага изгарянето на мазнините и повишава енергията.",
                            ImageUrl = "/products/FatBurner.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Нашата мощна термогенна формула ускорява метаболизма и помага на тялото да използва мастните депа като източник на енергия. Съдържа кофеин, зелен чай и Л-карнитин, които не само топят мазнините, но и повишават фокуса и издръжливостта по време на тренировка.",
                            Name = "Fat Burner",
                            Price = 54.90m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 6,
                            Category = "Отслабване",
                            Description = "Аминокиселина, която насърчава използването на мазнините като източник на енергия.",
                            ImageUrl = "/products/L-Carnitine.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Л-карнитинът е естествена аминокиселина, която играе ключова роля в транспортирането на мастни киселини до митохондриите, където те се изгарят за енергия. Идеален за прием 30 минути преди кардио тренировка за максимален ефект на изгаряне на мазнини.",
                            Name = "L-Carnitine",
                            Price = 39.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 7,
                            Category = "Отслабване",
                            Description = "Комбинация от билки и антиоксиданти за пречистване и метаболитен баланс.",
                            ImageUrl = "/products/DetoxFormula.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Detox Formula помага за изчистването на организма от токсини и задържана вода. С екстракти от глухарче, бял трън и зелен чай, този продукт подобрява храносмилането и подготвя тялото ви за по-ефективно усвояване на хранителните вещества.",
                            Name = "Detox Formula",
                            Price = 34.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 8,
                            Category = "Регенерация",
                            Description = "Подпомага мускулното възстановяване и намалява умората след тренировка.",
                            ImageUrl = "/products/GlumatineRecovery.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Глутаминът е най-често срещаната аминокиселина в мускулната тъкан. Допълнителният прием на Glutamine Recovery помага за попълване на запасите от гликоген, намалява мускулната болка и подсилва имунната система, която често се компрометира при тежки физически натоварвания.",
                            Name = "Glutamine Recovery",
                            Price = 46.90m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 9,
                            Category = "Регенерация",
                            Description = "Рибено масло с високо съдържание на EPA и DHA за стави и сърдечно здраве.",
                            ImageUrl = "/products/Omega-3.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Висококачествени Omega-3 мастни киселини, незаменими за здравето на сърцето, мозъка и очите. Те също така притежават силни противовъзпалителни свойства, които помагат за здравето на ставите и намаляват възпалението след тренировка.",
                            Name = "Omega-3",
                            Price = 29.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 10,
                            Category = "Регенерация",
                            Description = "Формула за по-здрави стави, сухожилия и кожа.",
                            ImageUrl = "/products/CollagenBoost.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Collagen Boost осигурява хидролизиран колаген тип I и III, обогатен с витамин C и хиалуронова киселина. Този комплекс укрепва ставите, сухожилията и връзките, като същевременно подобрява еластичността и хидратацията на кожата.",
                            Name = "Collagen Boost",
                            Price = 49.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 11,
                            Category = "Висока производителност",
                            Description = "Мощна енергийна напитка за експлозивни тренировки и издръжливост.",
                            ImageUrl = "/products/energyRush.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Заредете тренировката си с експлозивна енергия! Energy Rush съчетава бързи въглехидрати, кофеин и таурин, за да ви даде моментален тласък, който да продължи през цялата сесия. Бъдете спрени и фокусирани до последното повторение.",
                            Name = "Energy Rush",
                            Price = 35.90m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 12,
                            Category = "Висока производителност",
                            Description = "Аргинин и цитрулин за максимален мускулен напомпващ ефект.",
                            ImageUrl = "/products/pumpFormula.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Почувствайте как мускулите ви се пълнят с кръв с всяко повторение. Pump Formula разширява кръвоносните съдове благодарение на Аргинин и Цитрулин, осигурявайки по-добро снабдяване на мускулите с кислород и хранителни вещества за невероятен обем и васкуларност.",
                            Name = "Pump Formula",
                            Price = 42.90m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 13,
                            Category = "Висока производителност",
                            Description = "Формула за концентрация и енергия без срив.",
                            ImageUrl = "/products/FocusShot.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Малка доза, голям ефект. Focus Shot е концентрирана формула с ноотропици и витамини от група B, предназначена да изостри ума ви и да подобри концентрацията, без треперене или енергиен срив след това. Идеален за тренировки или интензивна умствена работа.",
                            Name = "Focus Shot",
                            Price = 27.90m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 14,
                            Category = "Имунитет",
                            Description = "Витамини от група B за енергия и имунна подкрепа.",
                            ImageUrl = "/products/VitaminB-3.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Ниацин (Витамин B-3) е от съществено значение за превръщането на храната в енергия. Той поддържа здравето на нервната система, кожата и храносмилателния тракт, като същевременно помага за намаляване на умората и отпадналостта.",
                            Name = "Vitamin B-3",
                            Price = 24.99m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 15,
                            Category = "Имунитет",
                            Description = "Комплекс от витамини и минерали за всекидневна защита.",
                            ImageUrl = "/products/Multivitamin.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Вашата дневна застраховка за здраве. Нашите мултивитамини покриват 100% от препоръчителния дневен прием на ключови микроелементи, подсилвайки имунитета и общото благосъстояние на активния човек.",
                            Name = "Multivitamin",
                            Price = 39.90m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 16,
                            Category = "Здравословна закуска",
                            Description = "Протеинови барчета с високо съдържание на белтъчини и фибри.",
                            ImageUrl = "/products/ProteinBarBox.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Вкусна и удобна закуска в движение. Всяко барче съдържа 20г висококачествен протеин и е с ниско съдържание на захар. Перфектният начин да задоволите глада за сладко, без да нарушавате диетата си.",
                            Name = "Protein Bar Box",
                            Price = 49.90m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 17,
                            Category = "Здравословна закуска",
                            Description = "Натурални овесени ядки за енергийна закуска.",
                            ImageUrl = "/products/Oats.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "100% натурални пълнозърнести овесени ядки. Източник на бавни въглехидрати и фибри, които осигуряват продължителна енергия и чувство на ситост. Идеални за сутрешна закуска или като добавка към протеиновия шейк.",
                            Name = "Oats",
                            Price = 19.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 18,
                            Category = "Здравословна закуска",
                            Description = "Фъстъчено масло без захар – източник на здравословни мазнини и протеин.",
                            ImageUrl = "/products/PeanutButter.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Чисто удоволствие на лъжица! Нашето фъстъчено масло е направено от 100% печени фъстъци, без добавена захар, сол или палмово масло. Естествен източник на протеини и здравословни мазнини.",
                            Name = "Peanut Butter",
                            Price = 29.90m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 19,
                            Category = "Облекло",
                            Description = "Спортна тениска от дишаща материя, идеална за тренировки.",
                            ImageUrl = "/images/products/PerformanceT-Shirtblack.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Тренирайте със стил и комфорт. Тази тениска е изработена от високотехнологична дишаща материя, която отвежда потта и ви държи сухи дори по време на най-интензивните сесии. Еластична кройка, която подчертава физиката.",
                            Name = "GymPower Тениска",
                            Price = 39.90m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 20,
                            Category = "Облекло",
                            Description = "Топъл и стилен суичър за спорт и свободно време.",
                            ImageUrl = "/products/GymPowerHodie.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Вашият нов любим суичър. Мека ватирана материя, модерен дизайн и удобна качулка. Перфектен за загряване преди тренировка или за релакс у дома след тежък ден.",
                            Name = "GymPower Суичър",
                            Price = 69.90m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 21,
                            Category = "Облекло",
                            Description = "Удобни фитнес ръкавици за по-добър захват и защита на дланите.",
                            ImageUrl = "/products/gympowergloves.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Защитете ръцете си от мазоли и подобрете захвата си. Тези ръкавици са с подсилени длани и дишаща горна част за максимален комфорт и здравина при работа с тежести.",
                            Name = "GymPower Ръкавици",
                            Price = 24.90m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 22,
                            Category = "Облекло",
                            Description = "Комплект тренировъчни ластици с различна сила на съпротивление.",
                            ImageUrl = "/products/gympowerband.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Тренирайте навсякъде с този комплект ластици. Включва 5 ластика с различно съпротивление, дръжки и колан за глезени. Перфектни за домашни тренировки, рехабилитация или загрявка.",
                            Name = "GymPower Ластици",
                            Price = 29.90m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 23,
                            Category = "Изграждане на мускулна маса",
                            Description = "Висококачествен суроватъчен протеин за растеж и възстановяване.",
                            ImageUrl = "/products/TrueWheyProtein.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "True Whey Protein е създаден за истински резултати. С висока биологична стойност и отличен вкус, той е идеалният партньор за всяка фитнес цел.",
                            Name = "True Whey Protein",
                            Price = 59.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 24,
                            Category = "Изграждане на мускулна маса",
                            Description = "Хидролизиран протеин без мазнини и захар за чисти резултати.",
                            ImageUrl = "/products/HydroWheyZero.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Най-чистата форма на протеин. Хидролизиран за супер бързо усвояване, без лактоза, без глутен и без захар. Перфектен за периоди на изчистване.",
                            Name = "Hydro Whey Zero",
                            Price = 64.99m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 25,
                            Category = "Изграждане на мускулна маса",
                            Description = "Изолат с 90% протеин за бързо възстановяване след интензивни тренировки.",
                            ImageUrl = "/products/PureIsoWhey.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Микрофилтриран суроватъчен изолат с изключителна чистота. Протеин, който достига до мускулите ви за минути. 0г мазнини, 0г въглехидрати.",
                            Name = "Pure IsoWhey",
                            Price = 69.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 26,
                            Category = "Регенерация",
                            Description = "Бавноусвоим протеин, който поддържа възстановяването по време на сън.",
                            ImageUrl = "/products/MiccelarCasein.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Нощното възстановяване е ключово. Мицеларният казеин осигурява бавно освобождаване на аминокиселини, предпазвайки мускулите ви през цялата нощ.",
                            Name = "Micellar Casein",
                            Price = 49.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 27,
                            Category = "Регенерация",
                            Description = "Чист креатин монохидрат за сила, обем и издръжливост.",
                            ImageUrl = "/products/CreatineMonohydrateCreapure.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Златният стандарт при креатина. 100% Creapure® формула за доказано повишаване на физическата сила и производителност при високоинтензивни тренировки.",
                            Name = "Creatine Monohydrate Creapure",
                            Price = 29.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 28,
                            Category = "Аминокиселини",
                            Description = "Аминокиселини с бързо усвояване за защита и растеж на мускулите.",
                            ImageUrl = "/products/BCAAInstant.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Мигновено разтворими BCAA аминокиселини. Освежаваща напитка, която поддържа мускулите хидратирани и нахранени по време на тренировка.",
                            Name = "BCAA Instant",
                            Price = 34.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 29,
                            Category = "Аминокиселини",
                            Description = "Пълен спектър есенциални аминокиселини за оптимална регенерация.",
                            ImageUrl = "/products/EAAMegaStack.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Всички 9 есенциални аминокиселини, от които тялото се нуждае за синтеза на протеин. Мощна формула за сериозни атлети.",
                            Name = "EAA Mega Stack",
                            Price = 39.99m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 30,
                            Category = "Предтренировъчни",
                            Description = "Подобрява кръвообращението и напомпването по време на тренировка.",
                            ImageUrl = "/products/CitrullineMalatePump.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Увеличете издръжливостта и намалете мускулната умора с Цитрулин Малат. Той подобрява кръвотока и доставката на хранителни вещества до мускулите.",
                            Name = "Citrulline Malate Pump",
                            Price = 27.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 31,
                            Category = "Аминокиселини",
                            Description = "Аргинин за повече сила и издръжливост.",
                            ImageUrl = "/products/ArginineAlpha-KetoGlutarate(AAKG).png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Високо бионалична форма на Аргинин. Стимулира производството на азотен оксид за по-добро напомпване и васкуларност.",
                            Name = "Arginine Alpha-KetoGlutarate (AAKG)",
                            Price = 25.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 32,
                            Category = "Предтренировъчни",
                            Description = "Формула за ментален фокус и устойчивост по време на тренировка.",
                            ImageUrl = "/products/FocusPowerFormula.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Останете в зоната. Тази формула ви помага да блокирате разсейванията и да се фокусирате изцяло върху всяко движение и повторение.",
                            Name = "Focus Power Formula",
                            Price = 33.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 33,
                            Category = "Предтренировъчни",
                            Description = "Бустер за по-добър мускулен обем и кръвоснабдяване.",
                            ImageUrl = "/products/Pump3D.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Триизмерно напомпване. Комбинация от азотни бустери и креатин за обем, плътност и сила.",
                            Name = "Pump 3D",
                            Price = 36.99m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 34,
                            Category = "Предтренировъчни",
                            Description = "Мощен бустер с кофеин и бета-аланин за експлозивна сила.",
                            ImageUrl = "/products/BlackBloodNoBooster.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Само за напреднали. Екстремна доза кофеин и стимуланти за най-тежките ви тренировки. Внимание: Висока ефикасност.",
                            Name = "Black Blood NO Booster",
                            Price = 44.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 35,
                            Category = "Предтренировъчни",
                            Description = "Предтренировъчна формула за моментален прилив на енергия.",
                            ImageUrl = "/products/NitroShotEnergy.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Течна енергия в удобна опаковка. Изпийте една ампула 15 минути преди тренировка и усетете разликата.",
                            Name = "Nitro Shot Energy",
                            Price = 32.99m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 36,
                            Category = "Предтренировъчни",
                            Description = "Експлозивен бустер за сила, енергия и фокус.",
                            ImageUrl = "/products/ThorPreWorkout.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Легендарният предтренировъчен продукт. Thor ви дава силата на бог за вашите тренировки.",
                            Name = "Thor PreWorkout",
                            Price = 39.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 37,
                            Category = "Имунитет",
                            Description = "Поддържа имунната система и възстановяването след натоварване.",
                            ImageUrl = "/products/VitaminC1000mg.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Мощен антиоксидант. Една таблетка дневно покрива нуждите ви от Витамин С, защитавайки клетките от оксидативен стрес.",
                            Name = "Vitamin C 1000mg",
                            Price = 14.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 38,
                            Category = "Витамини и Минерали",
                            Description = "Мултивитамини за жени с биотин, цинк и антиоксиданти.",
                            ImageUrl = "/products/VitaPinkForWomen.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Специално разработени за жени. Поддържат здравето на косата, кожата и ноктите, както и общия тонус и енергия.",
                            Name = "VitaPink For Women",
                            Price = 24.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 39,
                            Category = "Витамини и Минерали",
                            Description = "Подобрява съня, възстановяването и нивата на тестостерон.",
                            ImageUrl = "/products/Zinc+MagnesiumFormula.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "ZMA формула за атлети. Подобрява качеството на съня и подпомага естественото производство на анаболни хормони.",
                            Name = "Zinc + Magnesium Formula",
                            Price = 19.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 40,
                            Category = "Витамини и Минерали",
                            Description = "Мултивитаминен комплекс за енергия и здраве.",
                            ImageUrl = "/products/MultiComplex.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Всичко в едно. Витамини, минерали и ензими за цялостно здраве и жизненост.",
                            Name = "Multi Complex",
                            Price = 22.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 41,
                            Category = "Аксесоари",
                            Description = "Мека микрофибърна кърпа с лого GymPower – подходяща за фитнес.",
                            ImageUrl = "/products/GymTowelMicrofiber.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Бързосъхнеща, лека и компактна. Задължителен аксесоар за всяка тренировъчна чанта.",
                            Name = "Gym Towel Microfiber",
                            Price = 14.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 42,
                            Category = "Аксесоари",
                            Description = "Ластици с различно съпротивление за тренировка у дома и във фитнеса.",
                            ImageUrl = "/products/ResistanceBandOrange.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Универсален уред за тренировка. Използвайте за загрявка, стречинг или силови упражнения.",
                            Name = "Resistance Band",
                            Price = 29.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 43,
                            Category = "Аксесоари",
                            Description = "Професионални ръкавици за сигурен захват и защита.",
                            ImageUrl = "/products/TrainingGlovesPro.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Ергономичен дизайн и здрави материали. Предпазват ръцете ви и ви дават стабилност при всяко движение.",
                            Name = "Training Gloves Pro",
                            Price = 24.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 44,
                            Category = "Аксесоари",
                            Description = "Каишки за по-добър захват при тежки упражнения.",
                            ImageUrl = "/products/LiftingStraps.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Премахнете лимита на хвата си. Фокусирайте се върху целевия мускул, не върху предмишниците.",
                            Name = "Lifting Straps",
                            Price = 19.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 45,
                            Category = "Аксесоари",
                            Description = "Шейкър бутилка с вместимост 700 мл и вградено сито.",
                            ImageUrl = "/products/ShakerBottleElite700ml.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "100% непропусклив. Модерен дизайн, лесен за почистване, BPA free.",
                            Name = "Shaker Bottle Elite 700ml",
                            Price = 9.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 46,
                            Category = "Храни и Добавки",
                            Description = "Протеинов бар с вкус на шоколад и фъстъци.",
                            ImageUrl = "/products/ProteinBarDeluxe–ChocolatePeanut.jpg",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Декадентски вкус без вина. Шоколад, карамел и фъстъци в един протеинов бар.",
                            Name = "Protein Bar Deluxe – Chocolate Peanut",
                            Price = 3.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 47,
                            Category = "Мъжко облекло",
                            Description = "Мъжки спортни панталони с еластична талия и модерен дизайн.",
                            ImageUrl = "/products/JoggersCarbonGrey.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Удобство и стил от GymPower. Идеални за фитнес залата или за разходка в парка.",
                            Name = "GymPower Joggers Carbon Grey",
                            Price = 49.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 48,
                            Category = "Мъжко облекло",
                            Description = "Спортна тениска от дишаща материя, идеална за тренировка и ежедневие.",
                            ImageUrl = "/products/PerformanceTShirtBlack.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Класическо черно, модерна технология. Тениска, която работи толкова здраво, колкото и вие.",
                            Name = "Performance T-Shirt Black",
                            Price = 34.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 49,
                            Category = "Мъжко облекло",
                            Description = "Безръкавна фланелка с лого GymPower – за свобода и комфорт.",
                            ImageUrl = "/products/TrainingTankTopWhite.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Покажете резултатите от труда си. Свободна кройка за максимален обемен обхват на движение.",
                            Name = "Training Tank Top White",
                            Price = 29.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 50,
                            Category = "Мъжко облекло",
                            Description = "Суичър с контрастни оранжеви детайли и лого GymPower.",
                            ImageUrl = "/products/HoodieOrangeEdition.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Бъдете забележими. Ексклузивно издание в емблематичните цветове на GymPower.",
                            Name = "GymPower Hoodie Orange Edition",
                            Price = 54.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 51,
                            Category = "Мъжко облекло",
                            Description = "Еластични спортни шорти за тренировки и ежедневие.",
                            ImageUrl = "/products/ShortsFlexFit.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Леки и удобни. Вградена технология за отвеждане на потта.",
                            Name = "Shorts Flex Fit",
                            Price = 32.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 52,
                            Category = "Дамско облекло",
                            Description = "Безшевни клинове с висока талия за максимален комфорт.",
                            ImageUrl = "/products/SeamlessLeggingsCoral.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Втора кожа. Безшевна технология за нула протриване и максимален комфорт.",
                            Name = "Seamless Leggings Coral",
                            Price = 49.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 53,
                            Category = "Дамско облекло",
                            Description = "Спортен сутиен с отлична поддръжка и стилен дизайн.",
                            ImageUrl = "/products/SportBraPowerFit.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Сигурност и стил. Подходящ за високоинтензивни тренировки.",
                            Name = "Sport Bra Power Fit",
                            Price = 34.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 54,
                            Category = "Дамско облекло",
                            Description = "Модерен къс топ с лого GymPower – комфорт и визия.",
                            ImageUrl = "/products/CropTopBlackEdition.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Тренди визия за залата. Комбинира се перфектно с клинове с висока талия.",
                            Name = "Crop Top Black Edition",
                            Price = 29.99m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 55,
                            Category = "Дамско облекло",
                            Description = "Къси дамски панталонки с висока талия и мека материя.",
                            ImageUrl = "/products/HighWaistShortsPink.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Свеж цвят и удобна кройка. За слънчеви дни и горещи тренировки.",
                            Name = "High Waist Shorts Pink",
                            Price = 27.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 56,
                            Category = "Дамско облекло",
                            Description = "Оувърсайз суичър с модерна визия и комфортна кройка.",
                            ImageUrl = "/products/OversizedHoodieLilac.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            LongDescription = "Уют и мода. Страхотен люляков цвят и свободна кройка.",
                            Name = "Oversized Hoodie Lilac",
                            Price = 59.99m,
                            StockQuantity = 40
                        });
                });

            modelBuilder.Entity("GymPower.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/products/wheyprotein.png",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/products/wheyprotein.png",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/products/wheyprotein.png",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/products/massgainer.png",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/products/massgainer.png",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/products/massgainer.png",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/products/BCAAcomplex.png",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "/products/BCAAcomplex.png",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "/products/BCAAcomplex.png",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "/products/gaseinprotein.png",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "/products/gaseinprotein.png",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "/products/gaseinprotein.png",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "/products/FatBurner.png",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "/products/FatBurner.png",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "/products/FatBurner.png",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "/products/L-Carnitine.png",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "/products/L-Carnitine.png",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "/products/L-Carnitine.png",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "/products/DetoxFormula.png",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "/products/DetoxFormula.png",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "/products/DetoxFormula.png",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "/products/GlumatineRecovery.png",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "/products/GlumatineRecovery.png",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "/products/GlumatineRecovery.png",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "/products/Omega-3.png",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "/products/Omega-3.png",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "/products/Omega-3.png",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "/products/CollagenBoost.png",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "/products/CollagenBoost.png",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 30,
                            ImageUrl = "/products/CollagenBoost.png",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 31,
                            ImageUrl = "/products/energyRush.png",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 32,
                            ImageUrl = "/products/energyRush.png",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 33,
                            ImageUrl = "/products/energyRush.png",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 34,
                            ImageUrl = "/products/pumpFormula.png",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 35,
                            ImageUrl = "/products/pumpFormula.png",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 36,
                            ImageUrl = "/products/pumpFormula.png",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 37,
                            ImageUrl = "/products/FocusShot.png",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 38,
                            ImageUrl = "/products/FocusShot.png",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 39,
                            ImageUrl = "/products/FocusShot.png",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 40,
                            ImageUrl = "/products/VitaminB-3.png",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 41,
                            ImageUrl = "/products/VitaminB-3.png",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 42,
                            ImageUrl = "/products/VitaminB-3.png",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 43,
                            ImageUrl = "/products/Multivitamin.png",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 44,
                            ImageUrl = "/products/Multivitamin.png",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 45,
                            ImageUrl = "/products/Multivitamin.png",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 46,
                            ImageUrl = "/products/ProteinBarBox.png",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 47,
                            ImageUrl = "/products/ProteinBarBox.png",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 48,
                            ImageUrl = "/products/ProteinBarBox.png",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 49,
                            ImageUrl = "/products/Oats.png",
                            ProductId = 17
                        },
                        new
                        {
                            Id = 50,
                            ImageUrl = "/products/Oats.png",
                            ProductId = 17
                        },
                        new
                        {
                            Id = 51,
                            ImageUrl = "/products/Oats.png",
                            ProductId = 17
                        },
                        new
                        {
                            Id = 52,
                            ImageUrl = "/products/PeanutButter.png",
                            ProductId = 18
                        },
                        new
                        {
                            Id = 53,
                            ImageUrl = "/products/PeanutButter.png",
                            ProductId = 18
                        },
                        new
                        {
                            Id = 54,
                            ImageUrl = "/products/PeanutButter.png",
                            ProductId = 18
                        },
                        new
                        {
                            Id = 55,
                            ImageUrl = "/images/products/PerformanceT-Shirtblack.png",
                            ProductId = 19
                        },
                        new
                        {
                            Id = 56,
                            ImageUrl = "/images/products/PerformanceT-Shirtblack.png",
                            ProductId = 19
                        },
                        new
                        {
                            Id = 57,
                            ImageUrl = "/images/products/PerformanceT-Shirtblack.png",
                            ProductId = 19
                        },
                        new
                        {
                            Id = 58,
                            ImageUrl = "/products/GymPowerHodie.png",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 59,
                            ImageUrl = "/products/GymPowerHodie.png",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 60,
                            ImageUrl = "/products/GymPowerHodie.png",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 61,
                            ImageUrl = "/products/gympowergloves.png",
                            ProductId = 21
                        },
                        new
                        {
                            Id = 62,
                            ImageUrl = "/products/gympowergloves.png",
                            ProductId = 21
                        },
                        new
                        {
                            Id = 63,
                            ImageUrl = "/products/gympowergloves.png",
                            ProductId = 21
                        },
                        new
                        {
                            Id = 64,
                            ImageUrl = "/products/gympowerband.png",
                            ProductId = 22
                        },
                        new
                        {
                            Id = 65,
                            ImageUrl = "/products/gympowerband.png",
                            ProductId = 22
                        },
                        new
                        {
                            Id = 66,
                            ImageUrl = "/products/gympowerband.png",
                            ProductId = 22
                        },
                        new
                        {
                            Id = 67,
                            ImageUrl = "/products/TrueWheyProtein.png",
                            ProductId = 23
                        },
                        new
                        {
                            Id = 68,
                            ImageUrl = "/products/TrueWheyProtein.png",
                            ProductId = 23
                        },
                        new
                        {
                            Id = 69,
                            ImageUrl = "/products/TrueWheyProtein.png",
                            ProductId = 23
                        },
                        new
                        {
                            Id = 70,
                            ImageUrl = "/products/HydroWheyZero.png",
                            ProductId = 24
                        },
                        new
                        {
                            Id = 71,
                            ImageUrl = "/products/HydroWheyZero.png",
                            ProductId = 24
                        },
                        new
                        {
                            Id = 72,
                            ImageUrl = "/products/HydroWheyZero.png",
                            ProductId = 24
                        },
                        new
                        {
                            Id = 73,
                            ImageUrl = "/products/PureIsoWhey.png",
                            ProductId = 25
                        },
                        new
                        {
                            Id = 74,
                            ImageUrl = "/products/PureIsoWhey.png",
                            ProductId = 25
                        },
                        new
                        {
                            Id = 75,
                            ImageUrl = "/products/PureIsoWhey.png",
                            ProductId = 25
                        },
                        new
                        {
                            Id = 76,
                            ImageUrl = "/products/MiccelarCasein.png",
                            ProductId = 26
                        },
                        new
                        {
                            Id = 77,
                            ImageUrl = "/products/MiccelarCasein.png",
                            ProductId = 26
                        },
                        new
                        {
                            Id = 78,
                            ImageUrl = "/products/MiccelarCasein.png",
                            ProductId = 26
                        },
                        new
                        {
                            Id = 79,
                            ImageUrl = "/products/CreatineMonohydrateCreapure.png",
                            ProductId = 27
                        },
                        new
                        {
                            Id = 80,
                            ImageUrl = "/products/CreatineMonohydrateCreapure.png",
                            ProductId = 27
                        },
                        new
                        {
                            Id = 81,
                            ImageUrl = "/products/CreatineMonohydrateCreapure.png",
                            ProductId = 27
                        },
                        new
                        {
                            Id = 82,
                            ImageUrl = "/products/BCAAInstant.png",
                            ProductId = 28
                        },
                        new
                        {
                            Id = 83,
                            ImageUrl = "/products/BCAAInstant.png",
                            ProductId = 28
                        },
                        new
                        {
                            Id = 84,
                            ImageUrl = "/products/BCAAInstant.png",
                            ProductId = 28
                        },
                        new
                        {
                            Id = 85,
                            ImageUrl = "/products/EAAMegaStack.png",
                            ProductId = 29
                        },
                        new
                        {
                            Id = 86,
                            ImageUrl = "/products/EAAMegaStack.png",
                            ProductId = 29
                        },
                        new
                        {
                            Id = 87,
                            ImageUrl = "/products/EAAMegaStack.png",
                            ProductId = 29
                        },
                        new
                        {
                            Id = 88,
                            ImageUrl = "/products/CitrullineMalatePump.png",
                            ProductId = 30
                        },
                        new
                        {
                            Id = 89,
                            ImageUrl = "/products/CitrullineMalatePump.png",
                            ProductId = 30
                        },
                        new
                        {
                            Id = 90,
                            ImageUrl = "/products/CitrullineMalatePump.png",
                            ProductId = 30
                        },
                        new
                        {
                            Id = 91,
                            ImageUrl = "/products/ArginineAlpha-KetoGlutarate(AAKG).png",
                            ProductId = 31
                        },
                        new
                        {
                            Id = 92,
                            ImageUrl = "/products/ArginineAlpha-KetoGlutarate(AAKG).png",
                            ProductId = 31
                        },
                        new
                        {
                            Id = 93,
                            ImageUrl = "/products/ArginineAlpha-KetoGlutarate(AAKG).png",
                            ProductId = 31
                        },
                        new
                        {
                            Id = 94,
                            ImageUrl = "/products/FocusPowerFormula.png",
                            ProductId = 32
                        },
                        new
                        {
                            Id = 95,
                            ImageUrl = "/products/FocusPowerFormula.png",
                            ProductId = 32
                        },
                        new
                        {
                            Id = 96,
                            ImageUrl = "/products/FocusPowerFormula.png",
                            ProductId = 32
                        },
                        new
                        {
                            Id = 97,
                            ImageUrl = "/products/Pump3D.png",
                            ProductId = 33
                        },
                        new
                        {
                            Id = 98,
                            ImageUrl = "/products/Pump3D.png",
                            ProductId = 33
                        },
                        new
                        {
                            Id = 99,
                            ImageUrl = "/products/Pump3D.png",
                            ProductId = 33
                        },
                        new
                        {
                            Id = 100,
                            ImageUrl = "/products/BlackBloodNoBooster.png",
                            ProductId = 34
                        },
                        new
                        {
                            Id = 101,
                            ImageUrl = "/products/BlackBloodNoBooster.png",
                            ProductId = 34
                        },
                        new
                        {
                            Id = 102,
                            ImageUrl = "/products/BlackBloodNoBooster.png",
                            ProductId = 34
                        },
                        new
                        {
                            Id = 103,
                            ImageUrl = "/products/NitroShotEnergy.png",
                            ProductId = 35
                        },
                        new
                        {
                            Id = 104,
                            ImageUrl = "/products/NitroShotEnergy.png",
                            ProductId = 35
                        },
                        new
                        {
                            Id = 105,
                            ImageUrl = "/products/NitroShotEnergy.png",
                            ProductId = 35
                        },
                        new
                        {
                            Id = 106,
                            ImageUrl = "/products/ThorPreWorkout.png",
                            ProductId = 36
                        },
                        new
                        {
                            Id = 107,
                            ImageUrl = "/products/ThorPreWorkout.png",
                            ProductId = 36
                        },
                        new
                        {
                            Id = 108,
                            ImageUrl = "/products/ThorPreWorkout.png",
                            ProductId = 36
                        },
                        new
                        {
                            Id = 109,
                            ImageUrl = "/products/VitaminC1000mg.png",
                            ProductId = 37
                        },
                        new
                        {
                            Id = 110,
                            ImageUrl = "/products/VitaminC1000mg.png",
                            ProductId = 37
                        },
                        new
                        {
                            Id = 111,
                            ImageUrl = "/products/VitaminC1000mg.png",
                            ProductId = 37
                        },
                        new
                        {
                            Id = 112,
                            ImageUrl = "/products/VitaPinkForWomen.png",
                            ProductId = 38
                        },
                        new
                        {
                            Id = 113,
                            ImageUrl = "/products/VitaPinkForWomen.png",
                            ProductId = 38
                        },
                        new
                        {
                            Id = 114,
                            ImageUrl = "/products/VitaPinkForWomen.png",
                            ProductId = 38
                        },
                        new
                        {
                            Id = 115,
                            ImageUrl = "/products/Zinc+MagnesiumFormula.png",
                            ProductId = 39
                        },
                        new
                        {
                            Id = 116,
                            ImageUrl = "/products/Zinc+MagnesiumFormula.png",
                            ProductId = 39
                        },
                        new
                        {
                            Id = 117,
                            ImageUrl = "/products/Zinc+MagnesiumFormula.png",
                            ProductId = 39
                        },
                        new
                        {
                            Id = 118,
                            ImageUrl = "/products/MultiComplex.png",
                            ProductId = 40
                        },
                        new
                        {
                            Id = 119,
                            ImageUrl = "/products/MultiComplex.png",
                            ProductId = 40
                        },
                        new
                        {
                            Id = 120,
                            ImageUrl = "/products/MultiComplex.png",
                            ProductId = 40
                        },
                        new
                        {
                            Id = 121,
                            ImageUrl = "/products/GymTowelMicrofiber.png",
                            ProductId = 41
                        },
                        new
                        {
                            Id = 122,
                            ImageUrl = "/products/GymTowelMicrofiber.png",
                            ProductId = 41
                        },
                        new
                        {
                            Id = 123,
                            ImageUrl = "/products/GymTowelMicrofiber.png",
                            ProductId = 41
                        },
                        new
                        {
                            Id = 124,
                            ImageUrl = "/products/ResistanceBandOrange.png",
                            ProductId = 42
                        },
                        new
                        {
                            Id = 125,
                            ImageUrl = "/products/ResistanceBandOrange.png",
                            ProductId = 42
                        },
                        new
                        {
                            Id = 126,
                            ImageUrl = "/products/ResistanceBandOrange.png",
                            ProductId = 42
                        },
                        new
                        {
                            Id = 127,
                            ImageUrl = "/products/TrainingGlovesPro.png",
                            ProductId = 43
                        },
                        new
                        {
                            Id = 128,
                            ImageUrl = "/products/TrainingGlovesPro.png",
                            ProductId = 43
                        },
                        new
                        {
                            Id = 129,
                            ImageUrl = "/products/TrainingGlovesPro.png",
                            ProductId = 43
                        },
                        new
                        {
                            Id = 130,
                            ImageUrl = "/products/LiftingStraps.png",
                            ProductId = 44
                        },
                        new
                        {
                            Id = 131,
                            ImageUrl = "/products/LiftingStraps.png",
                            ProductId = 44
                        },
                        new
                        {
                            Id = 132,
                            ImageUrl = "/products/LiftingStraps.png",
                            ProductId = 44
                        },
                        new
                        {
                            Id = 133,
                            ImageUrl = "/products/ShakerBottleElite700ml.png",
                            ProductId = 45
                        },
                        new
                        {
                            Id = 134,
                            ImageUrl = "/products/ShakerBottleElite700ml.png",
                            ProductId = 45
                        },
                        new
                        {
                            Id = 135,
                            ImageUrl = "/products/ShakerBottleElite700ml.png",
                            ProductId = 45
                        },
                        new
                        {
                            Id = 136,
                            ImageUrl = "/products/ProteinBarDeluxe–ChocolatePeanut.jpg",
                            ProductId = 46
                        },
                        new
                        {
                            Id = 137,
                            ImageUrl = "/products/ProteinBarDeluxe–ChocolatePeanut.jpg",
                            ProductId = 46
                        },
                        new
                        {
                            Id = 138,
                            ImageUrl = "/products/ProteinBarDeluxe–ChocolatePeanut.jpg",
                            ProductId = 46
                        },
                        new
                        {
                            Id = 139,
                            ImageUrl = "/products/JoggersCarbonGrey.png",
                            ProductId = 47
                        },
                        new
                        {
                            Id = 140,
                            ImageUrl = "/products/JoggersCarbonGrey.png",
                            ProductId = 47
                        },
                        new
                        {
                            Id = 141,
                            ImageUrl = "/products/JoggersCarbonGrey.png",
                            ProductId = 47
                        },
                        new
                        {
                            Id = 142,
                            ImageUrl = "/products/PerformanceTShirtBlack.png",
                            ProductId = 48
                        },
                        new
                        {
                            Id = 143,
                            ImageUrl = "/products/PerformanceTShirtBlack.png",
                            ProductId = 48
                        },
                        new
                        {
                            Id = 144,
                            ImageUrl = "/products/PerformanceTShirtBlack.png",
                            ProductId = 48
                        },
                        new
                        {
                            Id = 145,
                            ImageUrl = "/products/TrainingTankTopWhite.png",
                            ProductId = 49
                        },
                        new
                        {
                            Id = 146,
                            ImageUrl = "/products/TrainingTankTopWhite.png",
                            ProductId = 49
                        },
                        new
                        {
                            Id = 147,
                            ImageUrl = "/products/TrainingTankTopWhite.png",
                            ProductId = 49
                        },
                        new
                        {
                            Id = 148,
                            ImageUrl = "/products/HoodieOrangeEdition.png",
                            ProductId = 50
                        },
                        new
                        {
                            Id = 149,
                            ImageUrl = "/products/HoodieOrangeEdition.png",
                            ProductId = 50
                        },
                        new
                        {
                            Id = 150,
                            ImageUrl = "/products/HoodieOrangeEdition.png",
                            ProductId = 50
                        },
                        new
                        {
                            Id = 151,
                            ImageUrl = "/products/ShortsFlexFit.png",
                            ProductId = 51
                        },
                        new
                        {
                            Id = 152,
                            ImageUrl = "/products/ShortsFlexFit.png",
                            ProductId = 51
                        },
                        new
                        {
                            Id = 153,
                            ImageUrl = "/products/ShortsFlexFit.png",
                            ProductId = 51
                        },
                        new
                        {
                            Id = 154,
                            ImageUrl = "/products/SeamlessLeggingsCoral.png",
                            ProductId = 52
                        },
                        new
                        {
                            Id = 155,
                            ImageUrl = "/products/SeamlessLeggingsCoral.png",
                            ProductId = 52
                        },
                        new
                        {
                            Id = 156,
                            ImageUrl = "/products/SeamlessLeggingsCoral.png",
                            ProductId = 52
                        },
                        new
                        {
                            Id = 157,
                            ImageUrl = "/products/SportBraPowerFit.png",
                            ProductId = 53
                        },
                        new
                        {
                            Id = 158,
                            ImageUrl = "/products/SportBraPowerFit.png",
                            ProductId = 53
                        },
                        new
                        {
                            Id = 159,
                            ImageUrl = "/products/SportBraPowerFit.png",
                            ProductId = 53
                        },
                        new
                        {
                            Id = 160,
                            ImageUrl = "/products/CropTopBlackEdition.png",
                            ProductId = 54
                        },
                        new
                        {
                            Id = 161,
                            ImageUrl = "/products/CropTopBlackEdition.png",
                            ProductId = 54
                        },
                        new
                        {
                            Id = 162,
                            ImageUrl = "/products/CropTopBlackEdition.png",
                            ProductId = 54
                        },
                        new
                        {
                            Id = 163,
                            ImageUrl = "/products/HighWaistShortsPink.png",
                            ProductId = 55
                        },
                        new
                        {
                            Id = 164,
                            ImageUrl = "/products/HighWaistShortsPink.png",
                            ProductId = 55
                        },
                        new
                        {
                            Id = 165,
                            ImageUrl = "/products/HighWaistShortsPink.png",
                            ProductId = 55
                        },
                        new
                        {
                            Id = 166,
                            ImageUrl = "/products/OversizedHoodieLilac.png",
                            ProductId = 56
                        },
                        new
                        {
                            Id = 167,
                            ImageUrl = "/products/OversizedHoodieLilac.png",
                            ProductId = 56
                        },
                        new
                        {
                            Id = 168,
                            ImageUrl = "/products/OversizedHoodieLilac.png",
                            ProductId = 56
                        });
                });

            modelBuilder.Entity("GymPower.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FitnessGoal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainingLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GymPower.Models.Order", b =>
                {
                    b.HasOne("GymPower.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymPower.Models.OrderItem", b =>
                {
                    b.HasOne("GymPower.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymPower.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GymPower.Models.ProductImage", b =>
                {
                    b.HasOne("GymPower.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GymPower.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("GymPower.Models.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("GymPower.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
