// <auto-generated />
using System;
using GymPower.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymPower.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251103133939_AddGymBeamProducts")]
    partial class AddGymBeamProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("GymPower.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GymPower.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("GymPower.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecommendedForMaintenance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecommendedForMassGain")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecommendedForWeightLoss")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Изграждане на мускулна маса",
                            Description = "Класически протеин за покачване на чиста мускулна маса и възстановяване.",
                            ImageUrl = "/products/wheyprotein.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Суроватъчен протеин",
                            Price = 69.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "Изграждане на мускулна маса",
                            Description = "Формула с високо съдържание на калории и въглехидрати за бързо покачване на тегло.",
                            ImageUrl = "/products/massgainer.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Mass Gainer",
                            Price = 84.90m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            Category = "Изграждане на мускулна маса",
                            Description = "Аминокиселини с разклонена верига за по-добра мускулна регенерация.",
                            ImageUrl = "/products/BCAAcomplex.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "BCAA Complex",
                            Price = 44.90m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 4,
                            Category = "Изграждане на мускулна маса",
                            Description = "Бавноусвоим протеин, идеален преди сън за дълготрайно възстановяване.",
                            ImageUrl = "/products/gaseinprotein.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Casein Protein",
                            Price = 59.90m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 5,
                            Category = "Отслабване",
                            Description = "Термогенна формула, която подпомага изгарянето на мазнините и повишава енергията.",
                            ImageUrl = "/products/FatBurner.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Fat Burner",
                            Price = 54.90m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 6,
                            Category = "Отслабване",
                            Description = "Аминокиселина, която насърчава използването на мазнините като източник на енергия.",
                            ImageUrl = "/products/L-Carnitine.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "L-Carnitine",
                            Price = 39.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 7,
                            Category = "Отслабване",
                            Description = "Комбинация от билки и антиоксиданти за пречистване и метаболитен баланс.",
                            ImageUrl = "/products/DetoxFormula.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Detox Formula",
                            Price = 34.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 8,
                            Category = "Регенерация",
                            Description = "Подпомага мускулното възстановяване и намалява умората след тренировка.",
                            ImageUrl = "/products/GlumatineRecovery.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Glutamine Recovery",
                            Price = 46.90m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 9,
                            Category = "Регенерация",
                            Description = "Рибено масло с високо съдържание на EPA и DHA за стави и сърдечно здраве.",
                            ImageUrl = "/products/Omega-3.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Omega-3",
                            Price = 29.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 10,
                            Category = "Регенерация",
                            Description = "Формула за по-здрави стави, сухожилия и кожа.",
                            ImageUrl = "/products/CollagenBoost.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Collagen Boost",
                            Price = 49.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 11,
                            Category = "Висока производителност",
                            Description = "Мощна енергийна напитка за експлозивни тренировки и издръжливост.",
                            ImageUrl = "/products/energyRush.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Energy Rush",
                            Price = 35.90m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 12,
                            Category = "Висока производителност",
                            Description = "Аргинин и цитрулин за максимален мускулен напомпващ ефект.",
                            ImageUrl = "/products/pumpFormula.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Pump Formula",
                            Price = 42.90m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 13,
                            Category = "Висока производителност",
                            Description = "Формула за концентрация и енергия без срив.",
                            ImageUrl = "/products/FocusShot.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Focus Shot",
                            Price = 27.90m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 14,
                            Category = "Имунитет",
                            Description = "Витамини от група B за енергия и имунна подкрепа.",
                            ImageUrl = "/products/VitaminB-3.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Vitamin B-3",
                            Price = 24.99m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 15,
                            Category = "Имунитет",
                            Description = "Комплекс от витамини и минерали за всекидневна защита.",
                            ImageUrl = "/products/Multivitamin.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Multivitamin",
                            Price = 39.90m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 16,
                            Category = "Здравословна закуска",
                            Description = "Протеинови барчета с високо съдържание на белтъчини и фибри.",
                            ImageUrl = "/products/ProteinBarBox.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Protein Bar Box",
                            Price = 49.90m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 17,
                            Category = "Здравословна закуска",
                            Description = "Натурални овесени ядки за енергийна закуска.",
                            ImageUrl = "/products/Oats.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Oats",
                            Price = 19.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 18,
                            Category = "Здравословна закуска",
                            Description = "Фъстъчено масло без захар – източник на здравословни мазнини и протеин.",
                            ImageUrl = "/products/PeanutButter.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Peanut Butter",
                            Price = 29.90m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 19,
                            Category = "Облекло",
                            Description = "Спортна тениска от дишаща материя, идеална за тренировки.",
                            ImageUrl = "/products/PerformanceT-Shirtblack.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "GymPower Тениска",
                            Price = 39.90m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 20,
                            Category = "Облекло",
                            Description = "Топъл и стилен суичър за спорт и свободно време.",
                            ImageUrl = "/products/GymPowerHodie.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "GymPower Суичър",
                            Price = 69.90m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 21,
                            Category = "Облекло",
                            Description = "Удобни фитнес ръкавици за по-добър захват и защита на дланите.",
                            ImageUrl = "/products/gympowergloves.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "GymPower Ръкавици",
                            Price = 24.90m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 22,
                            Category = "Облекло",
                            Description = "Комплект тренировъчни ластици с различна сила на съпротивление.",
                            ImageUrl = "/products/gympowerband.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "GymPower Ластици",
                            Price = 29.90m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 23,
                            Category = "Изграждане на мускулна маса",
                            Description = "Висококачествен суроватъчен протеин за растеж и възстановяване.",
                            ImageUrl = "/products/TrueWheyProtein.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "True Whey Protein",
                            Price = 59.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 24,
                            Category = "Изграждане на мускулна маса",
                            Description = "Хидролизиран протеин без мазнини и захар за чисти резултати.",
                            ImageUrl = "/products/HydroWheyZero.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Hydro Whey Zero",
                            Price = 64.99m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 25,
                            Category = "Изграждане на мускулна маса",
                            Description = "Изолат с 90% протеин за бързо възстановяване след интензивни тренировки.",
                            ImageUrl = "/products/PureIsoWhey.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Pure IsoWhey",
                            Price = 69.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 26,
                            Category = "Регенерация",
                            Description = "Бавноусвоим протеин, който поддържа възстановяването по време на сън.",
                            ImageUrl = "/products/MiccelarCasein.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Micellar Casein",
                            Price = 49.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 27,
                            Category = "Регенерация",
                            Description = "Чист креатин монохидрат за сила, обем и издръжливост.",
                            ImageUrl = "/products/CreatineMonohydrateCreapure.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Creatine Monohydrate Creapure",
                            Price = 29.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 28,
                            Category = "Аминокиселини",
                            Description = "Аминокиселини с бързо усвояване за защита и растеж на мускулите.",
                            ImageUrl = "/products/BCAAInstant.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "BCAA Instant",
                            Price = 34.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 29,
                            Category = "Аминокиселини",
                            Description = "Пълен спектър есенциални аминокиселини за оптимална регенерация.",
                            ImageUrl = "/products/EAAMegaStack.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "EAA Mega Stack",
                            Price = 39.99m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 30,
                            Category = "Предтренировъчни",
                            Description = "Подобрява кръвообращението и напомпването по време на тренировка.",
                            ImageUrl = "/products/CitrullineMalatePump.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Citrulline Malate Pump",
                            Price = 27.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 31,
                            Category = "Аминокиселини",
                            Description = "Аргинин за повече сила и издръжливост.",
                            ImageUrl = "/products/ArginineAlpha-KetoGlutarate(AAKG).png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Arginine Alpha-KetoGlutarate (AAKG)",
                            Price = 25.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 32,
                            Category = "Предтренировъчни",
                            Description = "Формула за ментален фокус и устойчивост по време на тренировка.",
                            ImageUrl = "/products/FocusPowerFormula.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Focus Power Formula",
                            Price = 33.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 33,
                            Category = "Предтренировъчни",
                            Description = "Бустер за по-добър мускулен обем и кръвоснабдяване.",
                            ImageUrl = "/products/Pump3D.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Pump 3D",
                            Price = 36.99m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 34,
                            Category = "Предтренировъчни",
                            Description = "Мощен бустер с кофеин и бета-аланин за експлозивна сила.",
                            ImageUrl = "/products/BlackBloodNoBooster.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Black Blood NO Booster",
                            Price = 44.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 35,
                            Category = "Предтренировъчни",
                            Description = "Предтренировъчна формула за моментален прилив на енергия.",
                            ImageUrl = "/products/NitroShotEnergy.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Nitro Shot Energy",
                            Price = 32.99m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 36,
                            Category = "Предтренировъчни",
                            Description = "Експлозивен бустер за сила, енергия и фокус.",
                            ImageUrl = "/products/ThorPreWorkout.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Thor PreWorkout",
                            Price = 39.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 37,
                            Category = "Имунитет",
                            Description = "Поддържа имунната система и възстановяването след натоварване.",
                            ImageUrl = "/products/VitaminC1000mg.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Vitamin C 1000mg",
                            Price = 14.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 38,
                            Category = "Витамини и Минерали",
                            Description = "Мултивитамини за жени с биотин, цинк и антиоксиданти.",
                            ImageUrl = "/products/VitaPinkForWomen.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "VitaPink For Women",
                            Price = 24.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 39,
                            Category = "Витамини и Минерали",
                            Description = "Подобрява съня, възстановяването и нивата на тестостерон.",
                            ImageUrl = "/products/Zinc+MagnesiumFormula.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Zinc + Magnesium Formula",
                            Price = 19.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 40,
                            Category = "Витамини и Минерали",
                            Description = "Мултивитаминен комплекс за енергия и здраве.",
                            ImageUrl = "/products/MultiComplex.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Multi Complex",
                            Price = 22.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 41,
                            Category = "Аксесоари",
                            Description = "Мека микрофибърна кърпа с лого GymPower – подходяща за фитнес.",
                            ImageUrl = "/products/GymTowelMicrofiber.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Gym Towel Microfiber",
                            Price = 14.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 42,
                            Category = "Аксесоари",
                            Description = "Ластици с различно съпротивление за тренировка у дома и във фитнеса.",
                            ImageUrl = "/products/ResistanceBandOrange.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Resistance Band",
                            Price = 29.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 43,
                            Category = "Аксесоари",
                            Description = "Професионални ръкавици за сигурен захват и защита.",
                            ImageUrl = "/products/TrainingGlovesPro.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Training Gloves Pro",
                            Price = 24.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 44,
                            Category = "Аксесоари",
                            Description = "Каишки за по-добър захват при тежки упражнения.",
                            ImageUrl = "/products/LiftingStraps.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Lifting Straps",
                            Price = 19.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 45,
                            Category = "Аксесоари",
                            Description = "Шейкър бутилка с вместимост 700 мл и вградено сито.",
                            ImageUrl = "/products/ShakerBottleElite700ml.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Shaker Bottle Elite 700ml",
                            Price = 9.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 46,
                            Category = "Храни и Добавки",
                            Description = "Протеинов бар с вкус на шоколад и фъстъци.",
                            ImageUrl = "/products/ProteinBarDeluxe–ChocolatePeanut.jpg",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Protein Bar Deluxe – Chocolate Peanut",
                            Price = 3.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 47,
                            Category = "Мъжко облекло",
                            Description = "Мъжки спортни панталони с еластична талия и модерен дизайн.",
                            ImageUrl = "/products/JoggersCarbonGrey.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "GymPower Joggers Carbon Grey",
                            Price = 49.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 48,
                            Category = "Мъжко облекло",
                            Description = "Спортна тениска от дишаща материя, идеална за тренировка и ежедневие.",
                            ImageUrl = "/products/PerformanceTShirtBlack.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Performance T-Shirt Black",
                            Price = 34.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 49,
                            Category = "Мъжко облекло",
                            Description = "Безръкавна фланелка с лого GymPower – за свобода и комфорт.",
                            ImageUrl = "/products/TrainingTankTopWhite.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Training Tank Top White",
                            Price = 29.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 50,
                            Category = "Мъжко облекло",
                            Description = "Суичър с контрастни оранжеви детайли и лого GymPower.",
                            ImageUrl = "/products/HoodieOrangeEdition.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "GymPower Hoodie Orange Edition",
                            Price = 54.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 51,
                            Category = "Мъжко облекло",
                            Description = "Еластични спортни шорти за тренировки и ежедневие.",
                            ImageUrl = "/products/ShortsFlexFit.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Shorts Flex Fit",
                            Price = 32.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 52,
                            Category = "Дамско облекло",
                            Description = "Безшевни клинове с висока талия за максимален комфорт.",
                            ImageUrl = "/products/SeamlessLeggingsCoral.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Seamless Leggings Coral",
                            Price = 49.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 53,
                            Category = "Дамско облекло",
                            Description = "Спортен сутиен с отлична поддръжка и стилен дизайн.",
                            ImageUrl = "/products/SportBraPowerFit.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Sport Bra Power Fit",
                            Price = 34.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 54,
                            Category = "Дамско облекло",
                            Description = "Модерен къс топ с лого GymPower – комфорт и визия.",
                            ImageUrl = "/products/CropTopBlackEdition.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Crop Top Black Edition",
                            Price = 29.99m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 55,
                            Category = "Дамско облекло",
                            Description = "Къси дамски панталонки с висока талия и мека материя.",
                            ImageUrl = "/products/HighWaistShortsPink.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "High Waist Shorts Pink",
                            Price = 27.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 56,
                            Category = "Дамско облекло",
                            Description = "Оувърсайз суичър с модерна визия и комфортна кройка.",
                            ImageUrl = "/products/OversizedHoodieLilac.png",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = false,
                            Name = "Oversized Hoodie Lilac",
                            Price = 59.99m,
                            StockQuantity = 40
                        });
                });

            modelBuilder.Entity("GymPower.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FitnessGoal")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GymPower.Models.Order", b =>
                {
                    b.HasOne("GymPower.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymPower.Models.OrderItem", b =>
                {
                    b.HasOne("GymPower.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymPower.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GymPower.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("GymPower.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
