// <auto-generated />
using System;
using GymPower.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymPower.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymPower.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GymPower.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("GymPower.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRecommendedForMaintenance")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecommendedForMassGain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecommendedForWeightLoss")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Protein",
                            Description = "High-quality whey protein for muscle recovery and growth",
                            ImageUrl = "/images/whey-protein.jpg",
                            IsRecommendedForMaintenance = true,
                            IsRecommendedForMassGain = true,
                            IsRecommendedForWeightLoss = true,
                            Name = "Whey Protein Premium",
                            Price = 59.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "Creatine",
                            Description = "Pure creatine for strength and performance",
                            ImageUrl = "/images/creatine.jpg",
                            IsRecommendedForMaintenance = true,
                            IsRecommendedForMassGain = true,
                            IsRecommendedForWeightLoss = false,
                            Name = "Creatine Monohydrate",
                            Price = 29.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 3,
                            Category = "Amino Acids",
                            Description = "Essential amino acids for muscle recovery",
                            ImageUrl = "/images/bcaa.jpg",
                            IsRecommendedForMaintenance = true,
                            IsRecommendedForMassGain = true,
                            IsRecommendedForWeightLoss = true,
                            Name = "BCAA Amino Acids",
                            Price = 39.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 4,
                            Category = "Weight Loss",
                            Description = "Advanced formula for weight management",
                            ImageUrl = "/images/fat-burner.jpg",
                            IsRecommendedForMaintenance = false,
                            IsRecommendedForMassGain = false,
                            IsRecommendedForWeightLoss = true,
                            Name = "Fat Burner Pro",
                            Price = 49.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 5,
                            Category = "Vitamins",
                            Description = "Complete vitamin formula for athletes",
                            ImageUrl = "/images/multivitamin.jpg",
                            IsRecommendedForMaintenance = true,
                            IsRecommendedForMassGain = true,
                            IsRecommendedForWeightLoss = true,
                            Name = "Multivitamin Complex",
                            Price = 24.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 6,
                            Category = "Pre-Workout",
                            Description = "Energy boost for intense workouts",
                            ImageUrl = "/images/pre-workout.jpg",
                            IsRecommendedForMaintenance = true,
                            IsRecommendedForMassGain = true,
                            IsRecommendedForWeightLoss = false,
                            Name = "Pre-Workout Energizer",
                            Price = 44.99m,
                            StockQuantity = 55
                        });
                });

            modelBuilder.Entity("GymPower.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FitnessGoal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 20, 14, 50, 25, 594, DateTimeKind.Local).AddTicks(3856),
                            Email = "admin@gympower.com",
                            FitnessGoal = "Maintenance",
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("GymPower.Models.Order", b =>
                {
                    b.HasOne("GymPower.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymPower.Models.OrderItem", b =>
                {
                    b.HasOne("GymPower.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymPower.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GymPower.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
